# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/G531GW/Desktop/Trabajo_SED_Basys_3/Trabajo_SED_Basys_3.srcs/sources_1/ip/clk_wiz_tetris/clk_wiz_tetris.xci
# IP: The module: 'clk_wiz_tetris' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/G531GW/Desktop/Trabajo_SED_Basys_3/Trabajo_SED_Basys_3.gen/sources_1/ip/clk_wiz_tetris/clk_wiz_tetris_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_tetris'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/G531GW/Desktop/Trabajo_SED_Basys_3/Trabajo_SED_Basys_3.gen/sources_1/ip/clk_wiz_tetris/clk_wiz_tetris.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_tetris'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/G531GW/Desktop/Trabajo_SED_Basys_3/Trabajo_SED_Basys_3.gen/sources_1/ip/clk_wiz_tetris/clk_wiz_tetris_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_tetris'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/G531GW/Desktop/Trabajo_SED_Basys_3/Trabajo_SED_Basys_3.srcs/sources_1/ip/clk_wiz_tetris/clk_wiz_tetris.xci
# IP: The module: 'clk_wiz_tetris' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/G531GW/Desktop/Trabajo_SED_Basys_3/Trabajo_SED_Basys_3.gen/sources_1/ip/clk_wiz_tetris/clk_wiz_tetris_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_tetris'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/G531GW/Desktop/Trabajo_SED_Basys_3/Trabajo_SED_Basys_3.gen/sources_1/ip/clk_wiz_tetris/clk_wiz_tetris.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_tetris'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/G531GW/Desktop/Trabajo_SED_Basys_3/Trabajo_SED_Basys_3.gen/sources_1/ip/clk_wiz_tetris/clk_wiz_tetris_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_tetris'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
